### ISSUE TITLE
关于下载文件乱码的问题

### ISSUE THREAD

**Issue by G-ZY** [renmu123/gb688_downloader#1]
你好，请问最后下载的PDF文件中是否存在乱码呢

**Comment by renmu123** [comment]
我当时参考的是[这位大佬](https://github.com/lzghzr/TampermonkeyJS/blob/master/GBdownload/GBdownload.user.js)的思路，我自己抓包抓了很久也没找到
网站里还有一个需要验证码才能下载的接口，验证码倒也只是最普通验证码，有兴趣的可以破解一下试试

**Comment by renmu123** [comment]
乱码的问题我暂时没有遇到，可以提供一下网址，我来查一下

**Comment by G-ZY** [comment]
http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=882F5B0D0BB9275EE75F4EDE05E9A114
![批注 2020-03-26 145426](https://user-images.githubusercontent.com/43690621/77618716-c7a9c100-6f71-11ea-83eb-9b4a0bed48f6.png)

**Comment by renmu123** [comment]
> http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=882F5B0D0BB9275EE75F4EDE05E9A114
> 就是下载后的PDF里面会有部分乱码

我刚才下载后大致翻了一下没看到有乱码，可以尝试换一个阅读器看看

**Comment by G-ZY** [comment]
非常感谢，我看了下，果然是微软浏览器的问题！

**Comment by renmu123** [comment]
> 我当时参考的是[这位大佬](https://github.com/lzghzr/TampermonkeyJS/blob/master/GBdownload/GBdownload.user.js)的思路，我自己抓包抓了很久也没找到
> 网站里还有一个需要验证码才能下载的接口，验证码倒也只是最普通验证码，有兴趣的可以破解一下试试

打开F12选择手机模式进行预览pdf，就可以抓到那几个包了
