### ISSUE TITLE
好像不能直接粘贴地址，只能一个个的输入

### ISSUE THREAD

**Issue by gh4492** [renmu123/gb688_downloader#2]
好像不能直接粘贴地址，只能一个个的输入，太麻烦了
另外，输入完了回车后，就退了，请问下载到哪里了呀？
我的系统是win10 64位

**Comment by renmu123** [comment]
1. 你试试能不能用右上角来黏贴，或者打开右上角控制台的"启用Crtl快捷键"
![image](https://user-images.githubusercontent.com/26896790/79813066-329dba80-83ad-11ea-9f2e-5618ee4c1ccf.png)
![image](https://user-images.githubusercontent.com/26896790/79813407-28c88700-83ae-11ea-8b6d-afb8895bbd72.png)
![image](https://user-images.githubusercontent.com/26896790/79813440-3e3db100-83ae-11ea-86fe-3d26d9cbffe6.png)

2. 因为这个打包的黑框是pyinstaller默认生成的，所以当代码出现错误信息的时候，会直接闪退。
你查看一下输入的国标网址是否正确（例如：http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=08C2A2B36DC07E5500A3EF5B09664FCC）。默认的下载位置和exe在同一个文件夹。

3. 之后可能会做一个GUI的版本，默认的实在坑太多
