### ISSUE TITLE
GUI 下载勾选问题以及卡住窗口不能出现下载信息框

### ISSUE THREAD

**Issue by Rhilip** [renmu123/gb688_downloader#4]
1. 仅支持下载搜索到整页，单个资源不能勾选。

![image](https://user-images.githubusercontent.com/13842140/90651347-79be8e00-e26f-11ea-944f-e7a3f276a02a.png)

2. 整页下载 国标 操作时会卡住窗口，导致不能出现下载框。有意思的是，我测试行标没问题。。

![image](https://user-images.githubusercontent.com/13842140/90651760-01a49800-e270-11ea-85bb-51db614f5bee.png)

**Comment by renmu123** [comment]
没有多选的的主要原因是我实在不熟悉怎么写 GUI ，同事又有 GUI 的需求，我就写了一个能用的出来。我在考虑使用 electron 进行重构（因为有足够的 UI 框架2333）

**Comment by huacong1** [comment]
我的也是，单个标准搜索出来打不开。下载页面也会出现同样停用的问题。

**Comment by renmu123** [comment]
可以使用最新的命令行程序（https://github.com/renmu123/gb688_downloader/releases）,gui应该是不会维护了
