### ISSUE TITLE
可以增加个自然资源标准化服务平台的下载吗

### ISSUE THREAD

**Issue by Lasx** [renmu123/gb688_downloader#5]
可以增加个自然资源标准化服务平台的下载吗
地址是这个

http://www.nrsis.org.cn/

**Comment by renmu123** [comment]
ok，等我有空的时候处理一下

**Comment by renmu123** [comment]
已经支持搜索和下载功能，  目前这个平台我还没用找到不能下载的标准，就没做错误处理。
由于原网页对pdf的处理是有多少页就要请求多少次，我也没做多线程等加速处理，速度可能会稍微慢那么一点点

    std = NatureStd()
    std.search("")
    std.download("http://www.nrsis.org.cn/portal/stdDetail/211166", "乡（镇）土地利用总体规划制图规范pdf")

**Comment by Lasx** [comment]
感谢，要方便很多了。自然资源部的规范全是扫描件，他应该也是一个pdf，我不太清楚为啥要每页都做分割。另外需要注意的是，国标他是引用的gb888的下载地址，会不会存在冲突？

**Comment by renmu123** [comment]
我还没注意到国标是跳转到gb688的，我加点逻辑处理一下

**Comment by renmu123** [comment]
> 感谢，要方便很多了。自然资源部的规范全是扫描件，他应该也是一个pdf，我不太清楚为啥要每页都做分割。另外需要注意的是，国标他是引用的gb888的下载地址，会不会存在冲突？

现在已经修复了

**Comment by Lasx** [comment]
棒
