### ISSUE TITLE
windows平台下如何使用？

### ISSUE THREAD

**Issue by ScienceZone** [renmu123/gb688_downloader#6]
您好，您的写的使用方法没看懂，能否再简明一点？我的是windows系统，win cli示例似乎没说怎么下载？我参考源码cli示例，下载std_cli.exe后，在其所在文件夹打开命令提示符窗口，在网页找到需要下载的国家标准，复制链接和文件名，输入如下指令：std_cli.exe  download http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=D3D826074D5E8B312506901909B1CDE3 航标灯光信号颜色.pdf，也能下载，但是对于在线预览的文档却会报错“Too many arguments.”，比如这个标准http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=B0695887A0C417E1587AC4F46E3A7AFB。因为我习惯用窗口工具，这种使用命令提示符运行的软件怎么用还是在网上搜到的，不知这样用是否是“标准方法”，正确的使用方法如何，能否下载只有在线预览的文档，请您指点，谢谢！

**Comment by renmu123** [comment]
关于 http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=B0695887A0C417E1587AC4F46E3A7AFB 这个文档的下载错误，你能截一个图吗？我没有复现到这个bug。
我有时间会再完善一下文档。

**Comment by ScienceZone** [comment]
问题找到了，文件名中不能有空格。现在就是希望使用方法简明一点，还有就是希望支持批量，找好需要的标准之后，一次下载完成，谢谢！



---原始邮件---
发件人: "renmu123"<notifications@github.com&gt;
发送时间: 2021年1月5日(周二) 上午9:54
收件人: "renmu123/gb688_downloader"<gb688_downloader@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ScienceZone"<forgxj@qq.com&gt;;
主题: Re: [renmu123/gb688_downloader] windows平台下如何使用？ (#6)




 
关于 http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=B0695887A0C417E1587AC4F46E3A7AFB 这个文档的下载错误，你能截一个图吗？我没有复现到这个bug。
 我有时间会再完善一下文档。

**Comment by renmu123** [comment]
你可以使用search函数，搜索相关的标准后进行批量下载。

之后会考虑直接读取文本来进行批量下载（我不太知道有没有这个需求）。

**Comment by ScienceZone** [comment]
不是相关搜索然后下载，大多数人应该想在网页精准搜到需要的每个标准，然后批量下载，谢谢



---原始邮件---
发件人: "renmu123"<notifications@github.com&gt;
发送时间: 2021年1月5日(周二) 中午11:56
收件人: "renmu123/gb688_downloader"<gb688_downloader@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ScienceZone"<forgxj@qq.com&gt;;
主题: Re: [renmu123/gb688_downloader] windows平台下如何使用？ (#6)




 
你可以使用search函数，搜索相关的标准后进行批量下载。
 
之后会考虑直接读取文本来进行批量下载（我不太知道有没有这个需求）。
