### ISSUE TITLE
国家标准网flash禁用导致接口的改变导致无法下载标准

### ISSUE THREAD

**Issue by renmu123** [renmu123/gb688_downloader#7]
已知问题：
1. 标准预览页报错
如：http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=D8AB02F0141FE11A4976E0E94FCF58B4
2. 其余标准因接口修改导致无法下载

**Comment by larryxiang** [comment]
+1

**Comment by renmu123** [comment]
采用了加密，我怕继续破解吃牢饭，有兴趣参考 https://github.com/lzghzr/TampermonkeyJS/issues/27 自行破解
